### ISSUE TITLE
Cannot Clone Repo

### ISSUE THREAD

**Issue by jereomyscott** [IGEL-Community/IGEL-OS-APP-RECIPES#24]
Hello I am trying to clone the repo using https and the IGEL App Creator website.  It gives me an error saying app.json not found in root.  It cannot clone the repo because of it.
![2024-12-23_13-45-59](https://github.com/user-attachments/assets/51610c26-7e8b-4eb3-894c-98c120a59c3a)

Any help would be great.  Thanks!

**Comment by rneher-igel** [comment]
What is it that you want to do?

**Comment by jereomyscott** [comment]
I am trying to use the IGEL App Creator site to make my application for me.  Attached is a better image.  I have the binaries, I just need the recipe.  I thought using the repo would work for the recipe - first time doing anything like this, and using git hub.
  
![2024-12-23_14-55-13](https://github.com/user-attachments/assets/1adb4cf3-cbcc-41a0-9a5d-773537ebad43)

**Comment by rneher-igel** [comment]
The GitHub site has some recipes that you can drop into `Upload Package'.

If you want to create a new recipe, then you need to manually create all the needed files for the recipe.

**Comment by jereomyscott** [comment]
Okay thanks!

**Comment by rneher-igel** [comment]
I would test SpeedCrunch first to test out the flow ...

click on `raw` to download the zip file

https://github.com/IGEL-Community/IGEL-OS-APP-RECIPES/blob/main/APP_Packages/Apps/speedcrunch_community.zip

Then drop into the App Creator Portal

**Comment by rneher-igel** [comment]
Details here:

https://igel-community.github.io/IGEL-Docs-v02/Docs/HOWTO-Add-Applications/#os-12-app-sdk-coming-soon

**Comment by jereomyscott** [comment]
Looking into this now.  Thanks for the additional details.  Will let you know what I end up with.

**Comment by jereomyscott** [comment]
Thanks man.  I am good to go for now!
